const state={image:false,analyzed:false,severity:'High',categories:[],history:[
 {id:'INS-001',site:'Hyderabad Manufacturing Unit',area:'Production Floor',risk:'PPE Violation',severity:'HIGH',score:82,date:'Today, 10:42',status:'Open'},
 {id:'INS-002',site:'Warehouse',area:'Storage Area',risk:'Blocked Exit',severity:'MEDIUM',score:91,date:'Yesterday',status:'Resolved'},
 {id:'INS-003',site:'Hyderabad Manufacturing Unit',area:'Electrical Room 02',risk:'Exposed wiring',severity:'HIGH',score:78,date:'Aug 21, 2026',status:'Open'},
 {id:'INS-004',site:'Hyderabad Manufacturing Unit',area:'Loading Bay',risk:'Clear inspection',severity:'LOW',score:96,date:'Aug 19, 2026',status:'Resolved'}
]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function icons(){if(window.lucide)lucide.createIcons()}
function localDate(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());$('#dateTime').value=d.toISOString().slice(0,16)}
function toast(msg){$('#toast span').textContent=msg;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),3200)}
function setImage(file){if(!file||!file.type.startsWith('image/'))return toast('Please upload a valid JPG or PNG image');if(file.size>10*1024*1024)return toast('Image must be smaller than 10MB');const reader=new FileReader();reader.onload=e=>{state.image=true;state.analyzed=false;$('#preview').src=e.target.result;$('#uploadPrompt').classList.add('hidden');$('#previewWrap').classList.remove('hidden');$('#analyzeBtn').disabled=false;$('#analysisStatus').innerHTML='<i data-lucide="image"></i> Evidence ready';icons();resetAnalysis()};reader.readAsDataURL(file)}
function resetAnalysis(){$('#analysisEmpty').classList.remove('hidden');$('#analysisLoading').classList.add('hidden');$('#analysisResults').classList.add('hidden');$('#detectedRisks').classList.add('hidden');$('#boxes').innerHTML=''}
function analyze(){if(!state.image)return;$('#analysisEmpty').classList.add('hidden');$('#analysisLoading').classList.remove('hidden');$('#analysisStatus').innerHTML='<i data-lucide="loader-circle"></i> Analyzing';icons();setTimeout(()=>{state.analyzed=true;$('#analysisLoading').classList.add('hidden');$('#analysisResults').classList.remove('hidden');$('#detectedRisks').classList.remove('hidden');$('#analysisStatus').innerHTML='<i data-lucide="check-circle-2"></i> Analysis complete';$('#analysisStatus').className='pending completed';$('#boxes').innerHTML='<div class="bbox" style="left:23%;top:16%;width:22%;height:60%"><span>Person · 98%</span></div><div class="bbox warning" style="left:52%;top:27%;width:27%;height:45%"><span>Electrical Panel · 87%</span></div>';icons();toast('AI analysis complete: 2 risks identified')},1800)}
function renderHistory(){const q=$('#searchInput').value.toLowerCase(),site=$('#filterSite').value,risk=$('#filterRisk').value,status=$('#filterStatus').value;const rows=state.history.filter(x=>(site==='all'||x.site===site)&&(risk==='all'||x.severity===risk)&&(status==='all'||x.status===status)&&Object.values(x).join(' ').toLowerCase().includes(q));$('#historyBody').innerHTML=rows.map(x=>`<tr><td class="id">${x.id}</td><td class="table-site"><b>${x.site}</b><small>${x.area}</small></td><td><b>${x.risk}</b></td><td><span class="table-tag table-${x.severity.toLowerCase()}">${x.severity}</span></td><td><b>${x.score}%</b></td><td>${x.date}</td><td><span class="status ${x.status==='Resolved'?'resolved':''}">${x.status}</span></td><td><button class="row-action" aria-label="View ${x.id}"><i data-lucide="more-horizontal"></i></button></td></tr>`).join('');$('#emptyState').classList.toggle('hidden',rows.length>0);icons()}
function save(){const required=['site','area','inspectionType','inspector','dateTime','location','description'];const missing=required.filter(id=>!$('#'+id).value.trim());if(!state.image){toast('Upload visual evidence before saving');return}if(missing.length){toast('Complete all inspection details before saving');$('#'+missing[0]).focus();return}if(!state.analyzed){toast('Analyze the image before saving this inspection');return}const num=String(state.history.length+1).padStart(3,'0');const risk=state.severity==='Low'?'Clear inspection':state.severity==='Medium'?'Blocked Emergency Area':'PPE Violation';state.history.unshift({id:`INS-${num}`,site:$('#site').value,area:$('#area').value,risk,severity:state.severity.toUpperCase(),score:state.severity==='High'?82:state.severity==='Medium'?88:95,date:'Just now',status:'Open'});$('#inspectionCount').textContent=Number($('#inspectionCount').textContent)+1;$('#activeRiskCount').textContent=Number($('#activeRiskCount').textContent)+1;$('#highRiskCount').textContent=state.severity==='High'||state.severity==='Critical'?Number($('#highRiskCount').textContent)+1:$('#highRiskCount').textContent;renderHistory();toast('Inspection saved successfully');document.querySelector('#history').scrollIntoView({behavior:'smooth',block:'start'})}
localDate();icons();renderHistory();
$('#browseBtn').onclick=()=>$('#imageInput').click();$('#imageInput').onchange=e=>setImage(e.target.files[0]);$('#removeImage').onclick=()=>{state.image=false;$('#imageInput').value='';$('#previewWrap').classList.add('hidden');$('#uploadPrompt').classList.remove('hidden');$('#analyzeBtn').disabled=true;resetAnalysis();$('#analysisStatus').innerHTML='<i data-lucide="circle-dashed"></i> Awaiting evidence';icons()};
const upload=$('#uploadArea');['dragenter','dragover'].forEach(e=>upload.addEventListener(e,x=>{x.preventDefault();upload.classList.add('dragging')}));['dragleave','drop'].forEach(e=>upload.addEventListener(e,x=>{x.preventDefault();upload.classList.remove('dragging')}));upload.addEventListener('drop',e=>setImage(e.dataTransfer.files[0]));
$('#analyzeBtn').onclick=analyze;$('#saveInspection').onclick=save;$('#addSite').onclick=()=>toast('Site creation is ready to connect to your REST API');$$('.category-pills button').forEach(b=>b.onclick=()=>{b.classList.toggle('selected');state.categories=$$('.category-pills .selected').map(x=>x.textContent)});$$('.severity-options button').forEach(b=>b.onclick=()=>{$$('.severity-options button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.severity=b.dataset.value});$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast(`${b.textContent.trim()} selected`)});['searchInput','filterSite','filterRisk','filterStatus'].forEach(id=>$('#'+id).addEventListener('input',renderHistory));
